name: 'Run app and tests'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

jobs:
  run-app-and-tests:
    name: Run app and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Insomnia Cli For OAS Spec Linting in CI
        run: |
          wget -q https://github.com/Kong/insomnia/releases/download/lib%409.1.0/inso-linux-9.1.0.tar.xz 
          tar -xf inso-linux-9.1.0.tar.xz
          ./inso --version
      - name: Lint Open API Specification
        run: ./inso lint spec burger_v1.yaml
        continue-on-error: true
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8
          cache: maven
      - name: Start App
        run: |
          cd burger 
          nohup ./mvnw spring-boot:run &
          for attempt in {1..20}; do sleep 1; if [ "$(curl --fail --silent localhost:8080/actuator/health)" = '{"status":"UP"}' ]; then echo ready; break; fi; echo waiting...; done
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Spectral Cli For OAS Spec Linting in CI 
        run: |
          npm install -g @stoplight/spectral-cli
          spectral lint burger_v2.yaml --ruleset oas_https_strict_rule_yaml.yaml
        continue-on-error: true
      - name: Install Node Dependencies
        run: npm install
      - name: Run newman tests
        run: |
          newman run BurgerAPI.postman_collection.json
      - name: Install Prism globally
        run: npm install -g @stoplight/prism-cli
      - name: Start Prism For Contract Testing
        run: nohup prism proxy burger_v1.yaml http://localhost:8080 > prism.log &
      - name: Invoke get burger API on Prism Mock Server
        run: |
          curl http://127.0.0.1:4010/v1/burgers/1
          cat prism.log
